# Custom Dockerfile that inherits from official Synapse image and adds our config files
FROM matrixdotorg/synapse:latest

# Copy our custom configuration files
COPY ./config/synapse/homeserver.yaml /conf/homeserver.yaml

# Copy specialized worker configurations
COPY ./config/synapse/event_persister.yaml /conf/event_persister.yaml
COPY ./config/synapse/typing_worker.yaml /conf/typing_worker.yaml
COPY ./config/synapse/to_device_worker.yaml /conf/to_device_worker.yaml
COPY ./config/synapse/presence_worker.yaml /conf/presence_worker.yaml
COPY ./config/synapse/receipts_worker.yaml /conf/receipts_worker.yaml
COPY ./config/synapse/push_rules_worker.yaml /conf/push_rules_worker.yaml
COPY ./config/synapse/device_lists_worker.yaml /conf/device_lists_worker.yaml
COPY ./config/synapse/account_data_worker.yaml /conf/account_data_worker.yaml

# Set working directory
WORKDIR /data
