worker_app: synapse.app.generic_worker
worker_name: event_persister
run_background_updates: false

worker_listeners:
  - port: 9094
    type: http
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [replication]
        compress: false
